version: '3.4'

services:
  books-api:
    image: books-api
    build:
      context: .
      dockerfile: bookstore-back/books-api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
  bookstore-front:
    image: bookstore-front
    build:
      context: .
      dockerfile: bookstore-front/Dockerfile
    ports:
      - "80:80"
    environment:
      - AUTH_API=http://localhost:63660
      - STORE_API=http://localhost:60822
    links: 
      - books-api